<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<a href="/timeline"><img src="/img/twitter_logo.png" class="menuIco" /></a>
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
								<span class="perfilPainelNome"><?= $this->view->info_user['username'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

					<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets['total_tweet'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_following['total_following'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_followers['total_followers'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="/quem_seguir" method="GET">
								<div class="input-group mb-3">
									<input type="text"  name="pesquisarPor" class="form-control" placeholder="De quem está a procura?">
									<div class="input-group-append">
										<button class="btn btn-primary"  type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<?php foreach ($this->view->users as $indice_arr => $user) : ?>

			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-6">
									<?= $user['username'] ?>
									
							
								</div>
							
								<div class="col-md-6 d-flex justify-content-end">
									<div>

										<?php if($user['follow_sn'] == 0) : ?>

										<a href="/acao?acao=seguir&id_user=<?=($user['id'])?>" class="btn btn-success">Seguir</a>

										<?php endif ?>

										<?php if($user['follow_sn'] == 1) : ?>

										<a href="/acao?acao=deixar_de_seguir&id_user=<?=($user['id'])?>" class="btn btn-danger">Deixar de seguir</a>

										<?php endif ?>

									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<?php endforeach ?>

		</div>
	</div>
</div>